// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.beayoscar.babynames.domain;

import com.beayoscar.babynames.domain.Gender;
import com.beayoscar.babynames.domain.Name;
import java.lang.Integer;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect NameDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NameDataOnDemand: @Component;
    
    private Random NameDataOnDemand.rnd = new SecureRandom();
    
    private List<Name> NameDataOnDemand.data;
    
    public Name NameDataOnDemand.getNewTransientName(int index) {
        Name obj = new Name();
        setDescription(obj, index);
        setGender(obj, index);
        setName(obj, index);
        setVote(obj, index);
        return obj;
    }
    
    public void NameDataOnDemand.setDescription(Name obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void NameDataOnDemand.setGender(Name obj, int index) {
        Gender gender = Gender.class.getEnumConstants()[0];
        obj.setGender(gender);
    }
    
    public void NameDataOnDemand.setName(Name obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void NameDataOnDemand.setVote(Name obj, int index) {
        Integer vote = 0;
        obj.setVote(vote);
    }
    
    public Name NameDataOnDemand.getSpecificName(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Name obj = data.get(index);
        return Name.findName(obj.getId());
    }
    
    public Name NameDataOnDemand.getRandomName() {
        init();
        Name obj = data.get(rnd.nextInt(data.size()));
        return Name.findName(obj.getId());
    }
    
    public boolean NameDataOnDemand.modifyName(Name obj) {
        return false;
    }
    
    public void NameDataOnDemand.init() {
        data = Name.findNameEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Name' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.beayoscar.babynames.domain.Name>();
        for (int i = 0; i < 10; i++) {
            Name obj = getNewTransientName(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
