// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.beayoscar.babynames.domain;

import com.beayoscar.babynames.domain.NameDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NameIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NameIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NameIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: NameIntegrationTest: @Transactional;
    
    @Autowired
    private NameDataOnDemand NameIntegrationTest.dod;
    
    @Test
    public void NameIntegrationTest.testCountNames() {
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", dod.getRandomName());
        long count = com.beayoscar.babynames.domain.Name.countNames();
        org.junit.Assert.assertTrue("Counter for 'Name' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NameIntegrationTest.testFindName() {
        com.beayoscar.babynames.domain.Name obj = dod.getRandomName();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to provide an identifier", id);
        obj = com.beayoscar.babynames.domain.Name.findName(id);
        org.junit.Assert.assertNotNull("Find method for 'Name' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Name' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NameIntegrationTest.testFindAllNames() {
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", dod.getRandomName());
        long count = com.beayoscar.babynames.domain.Name.countNames();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Name', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.beayoscar.babynames.domain.Name> result = com.beayoscar.babynames.domain.Name.findAllNames();
        org.junit.Assert.assertNotNull("Find all method for 'Name' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Name' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NameIntegrationTest.testFindNameEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", dod.getRandomName());
        long count = com.beayoscar.babynames.domain.Name.countNames();
        if (count > 20) count = 20;
        java.util.List<com.beayoscar.babynames.domain.Name> result = com.beayoscar.babynames.domain.Name.findNameEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Name' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Name' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NameIntegrationTest.testFlush() {
        com.beayoscar.babynames.domain.Name obj = dod.getRandomName();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to provide an identifier", id);
        obj = com.beayoscar.babynames.domain.Name.findName(id);
        org.junit.Assert.assertNotNull("Find method for 'Name' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyName(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Name' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NameIntegrationTest.testMerge() {
        com.beayoscar.babynames.domain.Name obj = dod.getRandomName();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to provide an identifier", id);
        obj = com.beayoscar.babynames.domain.Name.findName(id);
        boolean modified =  dod.modifyName(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.beayoscar.babynames.domain.Name merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Name' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NameIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", dod.getRandomName());
        com.beayoscar.babynames.domain.Name obj = dod.getNewTransientName(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Name' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Name' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NameIntegrationTest.testRemove() {
        com.beayoscar.babynames.domain.Name obj = dod.getRandomName();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Name' failed to provide an identifier", id);
        obj = com.beayoscar.babynames.domain.Name.findName(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Name' with identifier '" + id + "'", com.beayoscar.babynames.domain.Name.findName(id));
    }
    
}
